# Generated by Django 2.2.7 on 2020-06-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.FloatField()),
                ('price', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('source_web', models.CharField(max_length=50)),
                ('scrapped_date', models.DateField()),
                ('description', models.TextField()),
                ('extra_json_info', models.TextField()),
                ('property_type', models.CharField(choices=[('HO', 'House'), ('AP', 'Apartment'), ('FI', 'Field')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
